hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
  hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
  hl.exec_cmd("uwsm app -- hyprlock --no-fade-in")
  hl.exec_cmd("noctalia-shell")
end)
