{
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIIDNTCCAh2gAwIBAgIUSADhjw9eX77rxoi8zXJ6Vq1pUJswDQYJKoZIhvcNAQEL
      BQAwKDESMBAGA1UEAwwJbWl0bXByb3h5MRIwEAYDVQQKDAltaXRtcHJveHkwHhcN
      MjYwNzEwMDc0NDQ4WhcNMzYwNzA3MDc0NDQ4WjAoMRIwEAYDVQQDDAltaXRtcHJv
      eHkxEjAQBgNVBAoMCW1pdG1wcm94eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
      AQoCggEBAJnyH5LalY1IsT+V1NXLA23SY/GPkxu2l15usCcZeHCnriNabvDsUfza
      AWNzPIBw1Ehml4nKmosM5eUWZ1/Nzzy0Qo7mMLBsMnwM0ab3zagjJkrDfGh4A9dw
      VAbfr1rQY4TNQ5BGK1HhQD2AjmR5MT7xlG7wQZsH7nAjCcpTFeyvsMwIgE2gHeJe
      71WXO3R/JjEEhLppriWcfcIdEVYwZ4vygvI38SbIcdCZCd1SSPLulKg2pKoMq/nl
      NBXUE7mOuaXZNKLKiJtVngpxsGYLen6UmtcV/K7BEzfXpz4MhYpgGaygxo/nOpuG
      KjMfw+aV2DSRKcUwHHeq08SLJzkM54sCAwEAAaNXMFUwDwYDVR0TAQH/BAUwAwEB
      /zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
      FIL6oUVlS+N4TxdaMzzlE4ME+F/LMA0GCSqGSIb3DQEBCwUAA4IBAQBAVDWxOuw+
      j1VtMILi26iXZ/tdWCAkcn0XcyQ/zXIZ13cJ6j/rKaqH1P/oZhUfgxbp5oGBkM9R
      W4w82YS7yIUIfZdFmmrpSPs9ZsLQhSUUu5Yex6KUG4v4uzOuX/1Tyoy7WXYlJqPV
      nM2gtppFBh8xoyOYTXdRUEmSVSj0TLy/Z9+vUvHMBSMHf4K4bfTW+FKap0pNA3t2
      prONEOOvRTZ3v3aKKUPxNhW7B2uJwPvbQQlPcuKYSkXZccOCE8PLgjPkraJPsO1o
      WCt8hKxwV5JCxfbrjwqWMMv2tfLm7lv3jWmZhhQaXzFkqkk+FnRwAK9RM/R7O9JH
      52wWVJtLSRG9
      -----END CERTIFICATE-----
    ''
  ];
}
