{
  imports = [
    ./bluetooth.nix
    ./boot.nix
    ./certificates.nix
    ./graphics.nix
    ./handle-lid-switch.nix
    ./locale.nix
    ./media.nix
    ./net.nix
    ./nix.nix
    ./printing.nix
    ./secret-service.nix
    ./ssh.nix
    ./timezone.nix
    ./tuned.nix
    ./upower.nix
    ./usb.nix
    ./user.nix
    ./visual.nix
    ./zram.nix
  ];
}
